# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  browserpass = {
    pname = "browserpass";
    version = "3.7.2";
    src = fetchurl {
      url = "https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=108&x=id%3Dnaepdomgkenhinolocfifgehidddafch%26installsource%3Dondemand%26uc&extversion=3.7.2";
      sha256 = "sha256-eEKjfaqxLtiV/YuL2c59P7IkbnY6o3+1st4cEJQ7nr8=";
    };
    id = "naepdomgkenhinolocfifgehidddafch";
  };
  metamask = {
    pname = "metamask";
    version = "10.29.0";
    src = fetchurl {
      url = "https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=108&x=id%3Dnkbihfbeogaeaoehlefnkodbefgpgknn%26installsource%3Dondemand%26uc&extversion=10.29.0";
      sha256 = "sha256-GxMp4pPDX3qeh2cKTAVJfxXnddva+FLjEkvPdeeqplU=";
    };
    id = "nkbihfbeogaeaoehlefnkodbefgpgknn";
  };
  pricelabs = {
    pname = "pricelabs";
    version = "0.0.2.7";
    src = fetchurl {
      url = "https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=108&x=id%3Dahfbjnblgpemcceknnebmkjgbgkfdfod%26installsource%3Dondemand%26uc&extversion=0.0.2.7";
      sha256 = "sha256-S1hF+bbAK+lj2Tnue25N6m8dK1xJ8YXPQQQGmbcOP7Y=";
    };
    id = "ahfbjnblgpemcceknnebmkjgbgkfdfod";
  };
  rabby = {
    pname = "rabby";
    version = "0.82.0";
    src = fetchurl {
      url = "https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=108&x=id%3Dacmacodkjbdgmoleebolmdjonilkdbch%26installsource%3Dondemand%26uc&extversion=0.82.0";
      sha256 = "sha256-7vONGcorNZox1WXkyc+d3YKkpeUHwlwJczXwHTAGZwE=";
    };
    id = "acmacodkjbdgmoleebolmdjonilkdbch";
  };
  ublock-origin = {
    pname = "ublock-origin";
    version = "1.49.2";
    src = fetchurl {
      url = "https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=108&x=id%3Dcjpalhdlnbpafiamejdnhcphjbkeiagm%26installsource%3Dondemand%26uc&extversion=1.49.2";
      sha256 = "sha256-YW374iXwZYvmi9xzyXFbVu+k1/8iBPQsS37/pZCD12E=";
    };
    id = "cjpalhdlnbpafiamejdnhcphjbkeiagm";
  };
  urbit-visor = {
    pname = "urbit-visor";
    version = "0.4.2";
    src = fetchurl {
      url = "https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=108&x=id%3Doadimaacghcacmfipakhadejgalcaepg%26installsource%3Dondemand%26uc&extversion=0.4.2";
      sha256 = "sha256-WLNmQIi78Brd6+IDE/N1FUAXB1DkdGjVMchJS83gT8w=";
    };
    id = "oadimaacghcacmfipakhadejgalcaepg";
  };
}
