# get emacs-overlay cache hit using
# curl -L https://hydra.nix-community.org/job/emacs-overlay/unstable/emacsPgtk/latest | nix run nixpkgs#pup.out -- 'div#tabs-buildinputs'
[nixpkgs-emacs]
src.cmd = "echo 1a411f23ba299db155a5b45d5e145b85a7aafc42"
fetch.github = "NixOS/nixpkgs"

[emacs-overlay]
src.cmd = "echo ca955facdc9b29fde6dbd12823b7f4809fc5f18b"
fetch.github = "nix-community/emacs-overlay"

[modus-themes]
src.git = "https://github.com/protesilaos/modus-themes"
src.branch = "main"
fetch.github = "protesilaos/modus-themes"
