# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  emacs-overlay = {
    pname = "emacs-overlay";
    version = "ca955facdc9b29fde6dbd12823b7f4809fc5f18b";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "emacs-overlay";
      rev = "ca955facdc9b29fde6dbd12823b7f4809fc5f18b";
      fetchSubmodules = false;
      sha256 = "sha256-oQS3k66eZ77PE2dg5UaPn5QFc2v5U5KS3ufxWCG7QRc=";
    };
  };
  modus-themes = {
    pname = "modus-themes";
    version = "46919766bca4aa527a9a3bf77421182f4cf49594";
    src = fetchFromGitHub {
      owner = "protesilaos";
      repo = "modus-themes";
      rev = "46919766bca4aa527a9a3bf77421182f4cf49594";
      fetchSubmodules = false;
      sha256 = "sha256-J+55fOtTV9ItlyWgm9A6N8Mi8+1PB1OLSIxcixYPOjY=";
    };
    date = "2023-05-02";
  };
  nixpkgs-emacs = {
    pname = "nixpkgs-emacs";
    version = "1a411f23ba299db155a5b45d5e145b85a7aafc42";
    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "nixpkgs";
      rev = "1a411f23ba299db155a5b45d5e145b85a7aafc42";
      fetchSubmodules = false;
      sha256 = "sha256-6Va9iVtmmsw4raBc3QKvQT2KT/NGRWlvUlJj46zN8B8=";
    };
  };
}
