# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  emacs-overlay = {
    pname = "emacs-overlay";
    version = "2628f12023115c1b5e0fdff257cd2e1f4cc199b5";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "emacs-overlay";
      rev = "2628f12023115c1b5e0fdff257cd2e1f4cc199b5";
      fetchSubmodules = false;
      sha256 = "sha256-EyHLxmOnr5LhzT6zci84mOtiNmx7DGRRiY78DxG4FVA=";
    };
  };
  modus-themes = {
    pname = "modus-themes";
    version = "99b23d69836d10c76612cc5549faba4116ed85db";
    src = fetchFromGitHub {
      owner = "protesilaos";
      repo = "modus-themes";
      rev = "99b23d69836d10c76612cc5549faba4116ed85db";
      fetchSubmodules = false;
      sha256 = "sha256-/7BACUwFrwQfTVqdNjaUmkrL71JLvO99dyf+oGjIJMI=";
    };
    date = "2023-06-15";
  };
  nixpkgs-emacs = {
    pname = "nixpkgs-emacs";
    version = "7c67f006ea0e7d0265f16d7df07cc076fdffd91f";
    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "nixpkgs";
      rev = "7c67f006ea0e7d0265f16d7df07cc076fdffd91f";
      fetchSubmodules = false;
      sha256 = "sha256-tbJ9B8WLCTnVP/LwESRlg0dII6Zyg2LmUU/mB9Lu98E=";
    };
  };
}
