# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  widevine = {
    pname = "widevine";
    version = "4.10.2557.0";
    src = fetchurl {
      url = "https://dl.google.com/widevine-cdm/4.10.2557.0-linux-x64.zip";
      sha256 = "sha256-29C8D5UbUbBNF8thyjFlbu6Xm5XXcXyqhvNUKpOlQrI=";
    };
  };
}
