# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  tvheadend = {
    pname = "tvheadend";
    version = "73a6bd00d29421da04be5e1c41b2097fdc9c148b";
    src = fetchFromGitHub {
      owner = "tvheadend";
      repo = "tvheadend";
      rev = "73a6bd00d29421da04be5e1c41b2097fdc9c148b";
      fetchSubmodules = false;
      sha256 = "sha256-bU4XefIx8aC+PjqYF3ARq0b2TcpXQAhqhvOwuQr9r0A=";
    };
    date = "2024-04-26";
  };
}
