# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  tvheadend = {
    pname = "tvheadend";
    version = "dd82541c4c4c372a5b6af15e3dc0477f75c1b1bd";
    src = fetchFromGitHub {
      owner = "tvheadend";
      repo = "tvheadend";
      rev = "dd82541c4c4c372a5b6af15e3dc0477f75c1b1bd";
      fetchSubmodules = false;
      sha256 = "sha256-+z8Ps4LB2rTh0udpcnjIogULnOtQhj7fTIL97ukNPkw=";
    };
    date = "2024-08-28";
  };
}
