# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  keyd = {
    pname = "keyd";
    version = "41bcceef3c4c1876b5df0a5ba48812fa7c61d908";
    src = fetchFromGitHub ({
      owner = "rvaiya";
      repo = "keyd";
      rev = "41bcceef3c4c1876b5df0a5ba48812fa7c61d908";
      fetchSubmodules = false;
      sha256 = "sha256-dotfscZA5vfXxNsvVNMNhQqYjrZFPZuMN0Hgi8ojtFM=";
    });
    date = "2023-04-29";
  };
}
