# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  river = {
    pname = "river";
    version = "v0.2.3";
    src = fetchFromGitHub {
      owner = "riverwm";
      repo = "river";
      rev = "v0.2.3";
      fetchSubmodules = true;
      sha256 = "sha256-noZ2vo4J0cG3PN2k+2LzMc5WMtj0FEmMttE9obFH/tM=";
    };
  };
}
