# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  swhkd = {
    pname = "swhkd";
    version = "f965c0b9e6bbcede8c33f42fa618339dead0a061";
    src = fetchFromGitHub {
      owner = "oneingan";
      repo = "swhkd";
      rev = "f965c0b9e6bbcede8c33f42fa618339dead0a061";
      fetchSubmodules = false;
      sha256 = "sha256-H1iSVnRiydd2u2wjQ/dfdIcAorbqb/eJl1yidEHWtw0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./swhkd-f965c0b9e6bbcede8c33f42fa618339dead0a061/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2023-11-01";
  };
}
