# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  swhkd = {
    pname = "swhkd";
    version = "30f25b5bf99df5f16d91b51a7bd397c1de075085";
    src = fetchFromGitHub {
      owner = "waycrate";
      repo = "swhkd";
      rev = "30f25b5bf99df5f16d91b51a7bd397c1de075085";
      fetchSubmodules = false;
      sha256 = "sha256-K05v2xw7G/ZJsf62g696TOSZHMAOWf24sT9JcvvBNx0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./swhkd-30f25b5bf99df5f16d91b51a7bd397c1de075085/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2023-10-16";
  };
}
